### ISSUE TITLE
can't start DocksideBoot on IntelliJ IDEA

### ISSUE THREAD

**Issue by nabedge** [lastaflute/lastaflute-example-maihama#1]
![image](https://cloud.githubusercontent.com/assets/1396674/11607739/ef4c164e-9b96-11e5-98f9-8d7dbe091c14.png)

**Comment by jflute** [comment]
Thanks for your feedback.

Import dockside project only for now
and you can boot it.

I try to boot with importing all projects.

**Comment by jflute** [comment]
Anyway you can boot by adjusting current direction at Run Configuration for now

// from Japanese Twitter
https://twitter.com/jflute/status/673197020371267584

But I want to fix it not to depend on current directory...

**Comment by nabedge** [comment]
got ya! DocksideBoot and OrleansBoot started successfully.
![image](https://cloud.githubusercontent.com/assets/1396674/11618755/38cfef42-9ce2-11e5-94e5-669039cec5cc.png)

最終的にはこんな形になりました。サンプルとlasta-mixer2だけでなく場合によってはlastaflute本体にまでダイブする必要にせまられるかもしれないので、全部まとめたプロジェクトとして見えているほうが何かと好都合なのです。

![image](https://cloud.githubusercontent.com/assets/1396674/11618771/6343f700-9ce2-11e5-8121-d5f166add100.png)
